version: "3.9"

services:
    proxy:
        build:
            context: ./proxy

    redis:
        image: redis:6.2-alpine
        command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD?Require redis app password REDIS_PASSWORD} --maxmemory 256M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    backend:
        build:
            context: ./practice-works-backend
        environment:
            DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
            DB_APPLICATION_NAME: ${DB_APPLICATION_NAME}
            SERVICE_BASE_PATH: ${SERVICE_BASE_PATH}
            JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
            JWT_REFRESH_TOKEN_EXPIRE_DAYS: ${JWT_REFRESH_TOKEN_EXPIRE_DAYS}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
    frontend:
        build:
            context: ./practice-works-frontend
            args:
                NX_API_URL: ${NX_API_URL}
                NX_TELEGRAM_DISCUSSION: ${NX_TELEGRAM_DISCUSSION}
